import PrintContainer from "@/components/print/PrintContainer";
import { Receipt, User, Hash, CalendarDays } from "lucide-react";

export default function ReceiptPrint({ receipt }: any) {
  return (
    <PrintContainer>
      {/* HEADER */}
      <div className="text-center mb-6">
        <div className="flex justify-center items-center gap-2 mb-2">
          <Receipt size={28} />
          <h2 className="text-2xl font-bold tracking-wide">PAYMENT RECEIPT</h2>
        </div>
        <p className="text-base">Adeyemi Federal University of Education, Ondo</p>
      </div>

      {/* RECEIPT META */}
      <div className="grid grid-cols-2 gap-4 mb-6 text-sm">
        <div className="flex items-center gap-2">
          <Hash size={16} /> <strong>Receipt No:</strong> {receipt.receipt_no}
        </div>
        <div className="flex items-center gap-2">
          <CalendarDays size={16} /> <strong>Date:</strong> {receipt.date}
        </div>
        <div className="flex items-center gap-2">
          <User size={16} /> <strong>Name:</strong> {receipt.student_name}
        </div>
        <div className="flex items-center gap-2">
          <Hash size={16} /> <strong>Matric No:</strong> {receipt.matric_no}
        </div>
      </div>

      <hr className="my-4 border-black" />

      {/* TABLE */}
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr>
            <th className="border p-2 text-left">Description</th>
            <th className="border p-2 text-left">Amount (₦)</th>
          </tr>
        </thead>
        <tbody>
          {receipt.items.map((item: any, i: number) => (
            <tr key={i}>
              <td className="border p-2">{item.desc}</td>
              <td className="border p-2">{item.amount}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* TOTAL */}
      <div className="text-right mt-6 text-lg font-bold">
        Total: ₦{receipt.total}
      </div>

      <div className="mt-10 text-center text-xs opacity-70">
        Generated by AFUED Portal — Official Copy
      </div>
    </PrintContainer>
  );
}
